version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_golang
    environment:
      MYSQL_ROOT_PASSWORD: MY_ROOT
      MYSQL_DATABASE: my_first_db
      MYSQL_USER: my_golang
      MYSQL_PASSWORD: my_golang
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
